version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: clientes_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: clientes_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - clientes_net

  app:
    build: .
    container_name: clientes_app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./meu_app_php:/var/www/html:delegated
    environment:
      DB_HOST: db
      DB_USER: appuser
      DB_PASS: app_pass
      DB_NAME: clientes_db
      DB_PORT: 3306
    depends_on:
      - db
    networks:
      - clientes_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: clientes_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_pass
    depends_on:
      - db
    networks:
      - clientes_net

volumes:
  mysql_data:

networks:
  clientes_net:
    driver: bridge
